### ISSUE TITLE
Не понял смысл

### ISSUE THREAD

**Issue by alexeyqu** [nyotaL/game-LIFE-#2]
https://github.com/nyotaL/game-LIFE-/blob/d9655c1aaf163b1569983da94caeed9cacf5e856/set.py#L8

**Comment by alexeyqu** [comment]
Всё ещё не понял, поясни вот этот код:
```python
class parametrs:
    # определяем параметры и дизайн поля, его компонент
    SCREEN_X = 1300
    SCREEN_Y = 850
    CELL_SIZE = 10
def seting(a, b):
    if a <= 0:
        return b
    else:
        return a
# определяем параметры и дизайн поля, его компонент. Учитываем, что можем захотеть их поменять
SCREEN_X = seting(parametrs.SCREEN_X, 1300)
SCREEN_Y = seting(parametrs.SCREEN_Y, 850)
CELL_SIZE = seting(parametrs.CELL_SIZE, 10)
```
Почему не просто присваивать?

**Comment by nyotaL** [comment]
Для того, чтобы в случае если пользователь случайно идиот и хочет SCREEN_X = -1300, программа его могла поправить и сделать нормальный экран

**Comment by alexeyqu** [comment]
А если он идиот и хочет экран 1024.5?
Или "семнадцать" :)

**Comment by nyotaL** [comment]
теперь не сможет)

**Comment by alexeyqu** [comment]
Принято!
